server:
  port: 8082

spring:
  application:
    name: employee-service

  datasource:
    url: jdbc:postgresql://localhost:5435/employees
    username: employee_user
    password: employee_pass

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
